[general]
import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ]

[window]
decorations = "None"
padding = { x = 10, y = 10 }
dynamic_padding = true
startup_mode = "SimpleFullScreen"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
